import sys

def refactor():
    with open('src/wet_mcp/sources/docs.py', 'r') as f:
        lines = f.readlines()

    start_pos = -1
    for i, line in enumerate(lines):
        if 'async def fetch_docs_pages' in line:
            start_pos = i
            break

    if start_pos == -1:
        print("Could not find fetch_docs_pages")
        sys.exit(1)

    new_func = [
        "async def fetch_docs_pages(\n",
        "    docs_url: str,\n",
        "    query: str = \"\",\n",
        "    max_pages: int = 50,\n",
        "    batch_timeout: int = 45,\n",
        ") -> list[dict]:\n",
        "    \"\"\"Fetch documentation pages from a docs site with depth-2 crawling.\"\"\"\n",
        "    from wet_mcp.sources.crawler import extract\n",
        "\n",
        "    # SPA-friendly crawl settings\n",
        "    _SPA_KWARGS: dict = {\n",
        "        \"scan_full_page\": True,\n",
        "        \"delay_before_return_html\": 1.0,\n",
        "    }\n",
        "\n",
        "    docs_parsed = urlparse(docs_url)\n",
        "    ctx = DocsCrawlContext(\n",
        "        docs_url=docs_url,\n",
        "        docs_parsed=docs_parsed,\n",
        "        query=query,\n",
        "        max_pages=max_pages,\n",
        "        seen_urls={docs_url},\n",
        "        pending_urls=[],\n",
        "        pages=[],\n",
        "        is_github=\"github.com\" in docs_parsed.netloc,\n",
        "        gh_path_prefix=\"/\".join(docs_parsed.path.strip(\"/\").split(\"/\")[:2]),\n",
        "    )\n",
        "\n",
        "    # Step 1: Fetch root page\n",
        "    logger.info(f\"Fetching docs root: {docs_url}\")\n",
        "    try:\n",
        "        root_result_str = await asyncio.wait_for(\n",
        "            extract(urls=[docs_url], format=\"markdown\", stealth=True, **_SPA_KWARGS),\n",
        "            timeout=batch_timeout,\n",
        "        )\n",
        "        root_results = json.loads(root_result_str)\n",
        "    except TimeoutError:\n",
        "        logger.warning(f\"Root page fetch timed out after {batch_timeout}s: {docs_url}\")\n",
        "        return []\n",
        "    except Exception as e:\n",
        "        logger.error(f\"Failed to fetch root page {docs_url}: {e}\")\n",
        "        return []\n",
        "\n",
        "    # Detect redirect/version prefix\n",
        "    for r in root_results:\n",
        "        actual_url = r.get(\"url\", \"\")\n",
        "        if actual_url and actual_url != docs_url:\n",
        "            actual_parsed = urlparse(actual_url)\n",
        "            if actual_parsed.netloc == docs_parsed.netloc:\n",
        "                actual_path = actual_parsed.path.rstrip(\"/\")\n",
        "                actual_parts = [s for s in actual_path.split(\"/\") if s]\n",
        "                if len(actual_parts) >= 2:\n",
        "                    ctx.version_prefix = \"/\" + \"/\".join(actual_parts) + \"/\"\n",
        "                    ctx.seen_urls.add(actual_url)\n",
        "                    logger.info(f\"Detected version prefix: {ctx.version_prefix}\")\n",
        "            break\n",
        "\n",
        "    # Process root results\n",
        "    _process_crawl_results(root_results, ctx, discover_links=True)\n",
        "\n",
        "    # Early exit: if root page was blocked\n",
        "    if ctx.blocked_count > 0 and not ctx.pages:\n",
        "        logger.warning(f\"Root page blocked by bot protection, skipping crawl: {docs_url}\")\n",
        "        return ctx.pages\n",
        "\n",
        "    # Sitemap + objects.inv discovery\n",
        "    sitemap_task = _try_sitemap(docs_url, max_urls=max_pages)\n",
        "    inv_task = _try_objects_inv(docs_url, max_urls=max_pages)\n",
        "    try:\n",
        "        sitemap_urls, inv_urls = await asyncio.wait_for(\n",
        "            asyncio.gather(sitemap_task, inv_task),\n",
        "            timeout=batch_timeout,\n",
        "        )\n",
        "    except TimeoutError:\n",
        "        logger.warning(f\"Sitemap/objects.inv discovery timed out after {batch_timeout}s\")\n",
        "        sitemap_urls, inv_urls = [], []\n",
        "\n",
        "    # Merge extra URLs\n",
        "    inv_url_set = set(inv_urls)\n",
        "    extra_urls = list(inv_urls) + [u for u in sitemap_urls if u not in inv_url_set]\n",
        "    for su in extra_urls:\n",
        "        if su in inv_url_set:\n",
        "            # objects.inv URLs are trusted to be version-correct\n",
        "            if su not in ctx.seen_urls:\n",
        "                ctx.pending_urls.append(su)\n",
        "                ctx.seen_urls.add(su)\n",
        "        elif _filter_doc_url(su, ctx):\n",
        "            ctx.pending_urls.append(su)\n",
        "            ctx.seen_urls.add(su)\n",
        "\n",
        "    # Sort by query relevance\n",
        "    ctx.pending_urls = _sort_urls_by_query(ctx.pending_urls, query)\n",
        "\n",
        "    # --- Fetch round 1 ---\n",
        "    remaining = max_pages - len(ctx.pages)\n",
        "    if remaining > 0 and ctx.pending_urls:\n",
        "        round1_limit = min(len(ctx.pending_urls), remaining * 2 // 3 or remaining)\n",
        "        batch1_urls = ctx.pending_urls[:round1_limit]\n",
        "        ctx.pending_urls = ctx.pending_urls[round1_limit:]\n",
        "\n",
        "        logger.info(f\"Fetching {len(batch1_urls)} docs pages (round 1)...\")\n",
        "        try:\n",
        "            batch1_str = await asyncio.wait_for(\n",
        "                extract(urls=batch1_urls, format=\"markdown\", stealth=True, **_SPA_KWARGS),\n",
        "                timeout=batch_timeout,\n",
        "            )\n",
        "            _process_crawl_results(json.loads(batch1_str), ctx, discover_links=True)\n",
        "        except TimeoutError:\n",
        "            logger.warning(f\"Round 1 crawl timed out after {batch_timeout}s\")\n",
        "\n",
        "    # --- Fetch round 2 ---\n",
        "    remaining = max_pages - len(ctx.pages)\n",
        "    if remaining > 0 and ctx.pending_urls:\n",
        "        ctx.pending_urls = _sort_urls_by_query(ctx.pending_urls, query)\n",
        "        batch2_urls = ctx.pending_urls[:remaining]\n",
        "        if batch2_urls:\n",
        "            logger.info(f\"Fetching {len(batch2_urls)} docs pages (round 2)... \")\n",
        "            try:\n",
        "                batch2_str = await asyncio.wait_for(\n",
        "                    extract(urls=batch2_urls, format=\"markdown\", stealth=True, **_SPA_KWARGS),\n",
        "                    timeout=batch_timeout,\n",
        "                )\n",
        "                _process_crawl_results(json.loads(batch2_str), ctx, discover_links=False)\n",
        "            except TimeoutError:\n",
        "                logger.warning(f\"Round 2 crawl timed out after {batch_timeout}s\")\n",
        "\n",
        "    if ctx.blocked_count:\n",
        "        logger.warning(f\"Filtered {ctx.blocked_count} bot-protected pages from {docs_url}\")\n",
        "    logger.info(f\"Fetched {len(ctx.pages)} docs pages from {docs_url}\")\n",
        "    return ctx.pages\n"
    ]

    new_lines = lines[:start_pos] + new_func

    with open('src/wet_mcp/sources/docs.py', 'w') as f:
        f.writelines(new_lines)

if __name__ == "__main__":
    refactor()
